### Requisição para a raiz da aplicação
GET http://localhost:5274

### Requisição para listar livros
GET http://localhost:5274/biblioteca/livro/listar

### Requisição para cadastrar livros
POST http://localhost:5274/biblioteca/livro/cadastrar
Content-Type: application/json

{
    "titulo": "Água Viva",
    "autor": "Clarice Lispector",
    "qtdexemplares": 3,
    "genero": "Ficção Literária"
}

### Requisição para deleter livro especifico
DELETE http://localhost:5274/biblioteca/livro/deletar/a04308ec-f4ba-4c56-9b8c-187f9e4e9932

### Requisição para alterar livro específico
PUT http://localhost:5274/biblioteca/livro/alterar/e892daa8-2d41-4ca4-b224-159e02c1ca73
Content-Type: application/json

{
    "titulo": "Daisy Jones and The Six",
    "qtdexemplares": 1,
    "autor": "Taylor J. R."
}